// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: babies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBaby = `-- name: CreateBaby :one
INSERT INTO babies(
    full_name,
    birth_date
)
VALUES(
    $1,
    $2
)
RETURNING id, full_name, birth_date, created_at
`

type CreateBabyParams struct {
	FullName  string
	BirthDate pgtype.Date
}

func (q *Queries) CreateBaby(ctx context.Context, arg CreateBabyParams) (Baby, error) {
	row := q.db.QueryRow(ctx, createBaby, arg.FullName, arg.BirthDate)
	var i Baby
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}

const getBaby = `-- name: GetBaby :one
SELECT id, full_name, birth_date, created_at FROM babies
WHERE ID = $1
LIMIT 1
`

func (q *Queries) GetBaby(ctx context.Context, id pgtype.UUID) (Baby, error) {
	row := q.db.QueryRow(ctx, getBaby, id)
	var i Baby
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.BirthDate,
		&i.CreatedAt,
	)
	return i, err
}
