// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diaper_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiaperEvent = `-- name: CreateDiaperEvent :one
INSERT INTO diaper_events (
    baby_id, diaper_type, occurred_at, notes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, baby_id, occurred_at, created_at, diaper_type, notes
`

type CreateDiaperEventParams struct {
	BabyID     pgtype.UUID
	DiaperType string
	OccurredAt pgtype.Timestamptz
	Notes      string
}

func (q *Queries) CreateDiaperEvent(ctx context.Context, arg CreateDiaperEventParams) (DiaperEvent, error) {
	row := q.db.QueryRow(ctx, createDiaperEvent,
		arg.BabyID,
		arg.DiaperType,
		arg.OccurredAt,
		arg.Notes,
	)
	var i DiaperEvent
	err := row.Scan(
		&i.ID,
		&i.BabyID,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.DiaperType,
		&i.Notes,
	)
	return i, err
}

const listDiaperEventsByBaby = `-- name: ListDiaperEventsByBaby :many
SELECT id, baby_id, occurred_at, created_at, diaper_type, notes FROM diaper_events
WHERE baby_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT 20
`

func (q *Queries) ListDiaperEventsByBaby(ctx context.Context, babyID pgtype.UUID) ([]DiaperEvent, error) {
	rows, err := q.db.Query(ctx, listDiaperEventsByBaby, babyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaperEvent
	for rows.Next() {
		var i DiaperEvent
		if err := rows.Scan(
			&i.ID,
			&i.BabyID,
			&i.OccurredAt,
			&i.CreatedAt,
			&i.DiaperType,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
