// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diaper_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiaperEvent = `-- name: CreateDiaperEvent :one
INSERT INTO diaper_events (
    baby_id, diaper_type, occurred_at, created_at, notes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, baby_id, occurred_at, created_at, diaper_type, notes
`

type CreateDiaperEventParams struct {
	BabyID     pgtype.UUID
	DiaperType string
	OccurredAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Notes      string
}

func (q *Queries) CreateDiaperEvent(ctx context.Context, arg CreateDiaperEventParams) (DiaperEvent, error) {
	row := q.db.QueryRow(ctx, createDiaperEvent,
		arg.BabyID,
		arg.DiaperType,
		arg.OccurredAt,
		arg.CreatedAt,
		arg.Notes,
	)
	var i DiaperEvent
	err := row.Scan(
		&i.ID,
		&i.BabyID,
		&i.OccurredAt,
		&i.CreatedAt,
		&i.DiaperType,
		&i.Notes,
	)
	return i, err
}
