// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Baby struct {
	ID        pgtype.UUID
	FullName  string
	BirthDate pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type DiaperEvent struct {
	ID         pgtype.UUID
	BabyID     pgtype.UUID
	OccurredAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	DiaperType string
	Notes      string
}
