// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBaby(ctx context.Context, arg CreateBabyParams) (Baby, error)
	CreateDiaperEvent(ctx context.Context, arg CreateDiaperEventParams) (DiaperEvent, error)
	GetBaby(ctx context.Context, id pgtype.UUID) (Baby, error)
	ListDiaperEventsByBaby(ctx context.Context, babyID pgtype.UUID) ([]DiaperEvent, error)
}

var _ Querier = (*Queries)(nil)
